spring.application.name=cargo-tracking

# Veritabanı Bağlantı Ayarları
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Konsol SQL Ayarları
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Güvenlik Uyarısı Engelleme
spring.jpa.open-in-view=false